<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WinSight.AvMonitor</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinSight.Core\WinSight.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="WinSight.AvMonitor.Tests" />
  </ItemGroup>
</Project>
